commerce_payment.commerce_payment_gateway.plugin.paypal_payflow:
  type: commerce_payment_gateway_configuration
  mapping:
    partner:
      type: string
      label: 'Partner'
    vendor:
      type: string
      label: 'Vendor'
    user:
      type: string
      label: 'User'
    password:
      type: string
      label: 'Password'
