<?php

namespace Drupal\commerce_payflow;

/**
 * Defines the supported values for the result codes from Payflow.
 */
final class PayflowResultCode {
  const APPROVED = 0;

  const USER_AUTHENTICATION_FAILED = 1;

  const INVALID_TENDER_TYPE = 2;

  const INVALID_TRANSACTION_TYPE = 3;

  const INVALID_AMOUNT_FORMAT = 4;

  const INVALID_MERCHANT_INFORMATION = 5;

  const INVALID_CURRENCY_CODE = 6;

  const FIELD_FORMAT_ERROR = 7;

  const NOT_A_TRANSACTION_SERVER = 8;

  const INVALID_STREAM = 9;

  const TOO_MANY_LINE_ITEMS = 10;

  const CLIENT_TIMEOUT = 11;

  const DECLINED = 12;

  const REFERRAL = 13;

  const INVALID_CLIENT_CERTIFICATE_ID = 14;

  const MISSING_ORIGINAL_TRANSACTION_ID = 19;

  const MISSING_CUSTOMER_REFERENCE_NUMBER = 20;

  const INVALID_ABA_NUMBER = 22;

  const INVALID_ACCOUNT_NUMBER = 23;

  const INVALID_EXPIRATION_DATE = 24;

  const INVALID_HOST_MAPPING = 25;

  const INVALID_VENDOR_ACCOUNT = 26;

  const INSUFFICIENT_PARTNER_PERMISSIONS = 27;

  const INSUFFICIENT_USER_PERMISSIONS = 28;

  const INVALID_XML_DOCUMENT = 29;

  const DUPLICATE_TRANSACTION = 30;

  const ERROR_ADDING_RECURRING_PROFILE = 31;

  const ERROR_MODIFYING_RECURRING_PROFILE = 32;

  const ERROR_CANDELING_RECURRING_PROFILE = 33;

  const ERROR_FORCING_RECURRING_PROFILE = 34;

  const ERROR_REACTIVATING_RECURRING_PROFILE = 35;

  const OLTP_TRANSACTION_FAILED = 36;

  const INVALID_RECURRING_PROFILE_ID = 37;

  const INSUFFICIENT_FUNDS = 50;

  const EXCEEDS_PER_TRANSACTION_LIMIT = 51;

  const GENERAL_ERROR = 99;

  const TRANSACTION_TYPE_NOT_SUPPORTED = 100;

  const TIMEOUT_VALUE_TOO_SMALL = 101;

  const PROCESSOR_NOT_AVAILABLE = 102;

  const ERROR_READING_RESPONSE = 103;

  const TIMEOUT_WAITING_FOR_PROCESSOR = 104;

  const CREDIT_ERROR = 105;

  const HOST_NOT_AVAILABLE = 106;

  const DUPLICATE_SUPPRESSION_TIMEOUT = 107;

  const VOID_ERROR = 108;

  const TIMEOUT_WAITING_FOR_HOST = 109;

  const REFERENCED_AUTH_ERROR = 110;

  const CAPTURE_ERROR = 111;

  const FAILED_AVS_CHECK = 112;

  const TOTAL_WILL_EXCEED_SALES_CAP = 113;

  const CARD_SECURITY_CODE_MISMATCH = 114;

  const SYSTEM_BUSY = 115;

  const PAYPAL_INTERNAL_ERROR = 116;

  const FAILED_MERCHANT_CHECK_RULE = 117;

  const INVALID_KEYWORDS_IN_STRING_FIELDS = 118;

  const GENERAL_PIM_ADAPTER_FAILURE = 119;

  const ATTEMPT_TO_REFERENCE_FAILED_TRANSACTION = 120;

  const NOT_AN_ENABLED_FEATURE = 121;

  const TOTAL_WILL_EXCEED_CREDIT_CAP = 122;

  const DECLINED_BY_FRAUD_FILTERS = 125;

  const FLAGGED_FOR_REVIEW_BY_FRAUD_FILTERS = 126;

  const NOT_PROCESSED_BY_FRAUD_FILTERS = 127;

  const DECLINED_BY_MERCHANT_AFTER_FRAUD_REVIEW = 128;

  const VERSION_1_SDK_CLIENT_NO_LONGER_SUPPORTED = 131;

  const CARD_NOT_SUBMITTED_FOR_UPDATE = 132;

  const DATA_MISMATCH_IN_HTTP_RETRY = 133;

  const ISSUING_BANK_TIMEOUT = 150;

  const ISSUING_BANK_UNAVAILABLE = 151;

  const REAUTH_ERROR = 200;

  const ORDER_ERROR = 201;

  const PIM_ADAPTER_UNAVAILABLE = 402;

  const PIM_ADAPTER_STREAM_ERROR = 403;

  const PIM_ADAPTER_TIMEOUT = 404;

  const CYBERCASH_BATCH_ERROR = 600;

  const CYBERCASH_QUERY_ERROR = 601;

  const GENERIC_HOST_ERROR = 1000;

  const BUYER_AUTHENTICATION_UNAVAILABLE = 1001;

  const BUYER_AUTHENTICATION_TIMEOUT = 1002;

  const BUYER_AUTHENTICATION_INVALID_CLIENT_VERSION = 1003;

  const BUYING_AUTHENTICATION_INVALID_TIMEOUT_VALUE = 1004;

  const BUYER_AUTHENTICATION_UNAVAILABLE_2 = 1011;

  const BUYER_AUTHENTICATION_UNAVAILABLE_3 = 1012;

  const BUYER_AUTHENTICATION_UNAVAILABLE_4 = 1013;

  const BUYER_AUTHENTICATION_MERCHANT_NOT_ENROLLED = 1014;

  const BUYER_AUTHENTICATION_3D_SECURE_ERROR_RECEIVED = 1016;

  const BUYER_AUTHENTICATION_3D_SECURE_ERROR_INVALID = 1017;

  const BUYER_AUTHENTICATION_INVALID_CARD_TYPE = 1021;

  const BUYER_AUTHENTICATION_INVALID_CURRENCY_CODE = 1022;

  const BUYER_AUTHENTICATION_INVALID_MERCHANT_STATUS = 1023;

  const BUYER_AUTHENTICATION_FAILED_INVALID_PARES = 1041;

  const BUYER_AUTHENTICATION_FAILED_INVALID_PARES_FORMAT = 1042;

  const BUYER_AUTHENTICATION_FAILED_CANNOT_FIND_SUCCESSFUL_ENROLLMENT = 1043;

  const BUYER_AUTHENTICATION_FAILED_PARES_SIGNATURE_VALIDATION_FAILED = 1044;

  const BUYER_AUTHENTICATION_FAILED_PARES_AMOUNT_INVALID = 1045;

  const BUYER_AUTHENTICATION_FAILED_PARES_ACQUIRER_INVALID = 1046;
}
